services:
  - docker

notifications:
  email:
    recipients:
      - cc@monexa.co.uk
    on_success: always
    on_failure: always

script:
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  - docker build --target test --tag todo-app-test .
  - docker run --env-file ./.env.test todo-app-test src/tests
  - docker run --env-file "./.env.test_e2e" -e MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING -e MONGO_DB_NAME=$MONGO_DB_NAME todo-app-test src/tests_e2e
  - docker build --target production --tag $DOCKER_HUB_USERNAME/todo-app:latest .

before_deploy:
  - docker push $DOCKER_HUB_USERNAME/todo-app:latest

deploy:
  - provider: script
    script: bash build_scripts/deploy.sh $AZURE_DEPLOYMENT_WEBHOOK_URL
    on:
      branch: master