version: "3.8"

services:
  todo_app:
    build:
      context: .
      target: production
    image: todo-app:production
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    env_file:
     - ./.env