version: "3.8"

services:
  todo_app:
    build:
      context: .
      target: development
    image: todo-app:development
    ports:
      - "5000:5000"
    env_file:
     - ./.env
    volumes:
      - type: bind
        source: ./src
        target: /src